### ISSUE TITLE
Unable to remove subscriptions

### ISSUE THREAD

**Issue by Flinch** [mattermost/mattermost-app-trello#5]
I am unable to remove subscriptions. I get hit with an invalid ID error. See screenshot below. 

<img width="1192" alt="Screen Shot 2023-01-26 at 11 27 17 PM" src="https://user-images.githubusercontent.com/8286670/215009386-ff6570b9-26d1-4f9f-8794-dd7715994812.png">

**Comment by LizSegura98** [comment]
@Flinch For this issue, the app is deployed in AWS or in HTTP? Which value is used to delete the subscription?

**Comment by LizSegura98** [comment]
Hi @Flinch, this was solved in last commit [73ed9e9](https://github.com/mattermost/mattermost-app-trello/pull/2/commits/73ed9e92f52e3f7b064f91541e07a22fe88adca2). could you help me to test it?

**Comment by Flinch** [comment]
Fix verified
